config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  resources :conversations, only: :index

  resources :users, only: :show

  resources :conversations do
    resources :messages, only: :create
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  has_many :participants, dependent: :destroy

  validates :name, uniqueness: true

  scope :public_conversations, -> { where(is_private: false) }

  after_create_commit {broadcast_append_to "conversations"}
  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to "conversations" unless self.is_private
  end

  def self.create_private_conversation(users, conversation_name)
    single_conversation = Conversation.create(name: conversation_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, conversation_id: single_conversation.id)
    end
    single_conversation
  end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { broadcast_append_to self.conversation }

  belongs_to :conversation
  belongs_to :user

  validates :content, presence: true

end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true, uniqueness: true

  has_many :messages
  has_many :conversations

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])


    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def create
    @conversation = Conversation.create(name: params["conversation"]["name"])
  end

  def show
    @current_user = current_user
    @message = Message.new
    @single_conversation = Conversation.find(params[:id])
    @conversations = Conversation.public_conversations
    @users = User.all_except(@current_user)
    @conversation = Conversation.new
    @messages = @single_conversation.messages

    render "index"
  end

  def index
    @current_user = current_user
    @conversations = Conversation.public_conversations
    @users = User.all_except(@current_user)

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @current_user = current_user
    @message = @current_user.messages.create(content: msg_params[:content], conversation_id: params[:conversation_id])
  end

  private

  def msg_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @conversations = Conversation.public_conversations
    @users = User.all_except(@current_user)
    @conversation = Conversation.new
    @message = Message.new
    @conversation_name = get_name(@user, @current_user)
    @single_conversation = Conversation.where(name: @conversation_name).first || Conversation.create_private_conversation([@user, @current_user], @conversation_name)
    @messages = @single_conversation.messages

    render "conversations/index"
  end

  private
  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<div> <%= link_to conversation.name, conversation %> </div>

app/views/conversations/index.html.erb
<%= render "shared/navbar" %>

<div class="container p-2">
  <div class="row">
    <div class="col-md-2">
      <h4> Contacts </h4>
      <div>
        <%= turbo_stream_from "users" %>
          <div id="users">
            <% if user_signed_in? %>
              <%= render @users %>
            <% end %>
          </div>
      </div>
    </div>

    <div class="col-md-10 bg-dark text-light">
      <% if @single_conversation %>
        <h4 class="text-center"> <%= @user&.first_name %> </h4>
        <%= turbo_stream_from @single_conversation %>
          <div id="messages">
            <%= render @messages %>
          </div>
            <%= render partial: 'layouts/new_message_form' %>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container conversation">
  <h1><%= @conversation.name %></h1>

  <div class="messages">
    <% @conversation.messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <small>
          <strong><%= message.user.first_name %></strong>
          <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </small>
        <p><%= message.content %></p>
      </div>
    <% end %>
  </div>
</div>

<%= simple_form_for [@conversation, @message],
  html: {class: "d-flex"} do |f|
%>
  <%= f.input :content,
    label: false,
    placeholder: "Message ##{@conversation.name}",
    wrapper_html: {class: "flex-grow-1"}
  %>
  <%= f.submit "Send", class: "btn btn-primary mb-3" %>
<% end %>

app/views/layouts/_new_conversation_form.html.erb
<%= form_with(model: @conversation, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/_new_message_form.html.erb
<div class="msg-form">
  <%= form_with(model: [@single_conversation ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit "Envoyer", data: { disable_with: false }, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatsAppClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <% unless message.conversation.is_private %>
      <h6 class="name"> <%= message.user.first_name %> </h6>
    <% end %>
  <%= message.content %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/navbar" %>

app/views/shared/_navbar.html.erb
<div class="container-home">

  <h1> Welcome on WhatsApp</h1>

  <h3> A messaging app for friends and more</h3>

    <div class="links">
      <% if user_signed_in?  && current_page?(root_path)%>
        <%= link_to "Mes conversations", conversations_path %>
      <% end %>

      <% if user_signed_in? == false %>
        <%= link_to "Connecte toi", new_user_session_path %>
      <% end %>

      <% if user_signed_in? == false %>
        <%= link_to "S'inscrire", new_user_registration_path %>
      <% end %>

      <% if user_signed_in? %>
          <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %>
      <% end %>

      <% if user_signed_in?  && current_page?(conversations_path)%>
        <%= link_to "Accueil", root_path %>
      <% end %>

    </div>

</div>

app/views/users/_user.html.erb
<div> <%= link_to user.first_name, user %> </div>

app/views/users/index.html.erb
<%= render "shared/navbar" %>

<div class="container-home">

  <h1>WhatsApp</h1>

</div>
<ul>
  <% @users.each do |user| %>
    <li><%= user.first_name %></li>
  <% end %>
</ul>